In [1]:
import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
cv.resize()

In [3]:
x = 2
x**2

4

In [4]:
print('UTAR is great!')

UTAR is great!


# demo

In [11]:
for i in range(100):
    print(f'Iteration #{i}')

Iteration #0
Iteration #1
Iteration #2
Iteration #3
Iteration #4
Iteration #5
Iteration #6
Iteration #7
Iteration #8
Iteration #9
Iteration #10
Iteration #11
Iteration #12
Iteration #13
Iteration #14
Iteration #15
Iteration #16
Iteration #17
Iteration #18
Iteration #19
Iteration #20
Iteration #21
Iteration #22
Iteration #23
Iteration #24
Iteration #25
Iteration #26
Iteration #27
Iteration #28
Iteration #29
Iteration #30
Iteration #31
Iteration #32
Iteration #33
Iteration #34
Iteration #35
Iteration #36
Iteration #37
Iteration #38
Iteration #39
Iteration #40
Iteration #41
Iteration #42
Iteration #43
Iteration #44
Iteration #45
Iteration #46
Iteration #47
Iteration #48
Iteration #49
Iteration #50
Iteration #51
Iteration #52
Iteration #53
Iteration #54
Iteration #55
Iteration #56
Iteration #57
Iteration #58
Iteration #59
Iteration #60
Iteration #61
Iteration #62
Iteration #63
Iteration #64
Iteration #65
Iteration #66
Iteration #67
Iteration #68
Iteration #69
Iteration #70
Iteration #71
It

In [14]:
%pwd

'C:\\Users\\User\\image processing\\image_processing_UCCC2513'

In [17]:
%env

{'ALLUSERSPROFILE': 'C:\\ProgramData',
 'APPDATA': 'C:\\Users\\User\\AppData\\Roaming',
 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files',
 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files',
 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files',
 'COMPUTERNAME': 'LAPTOP-N2AJGH91',
 'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe',
 'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData',
 'FPS_BROWSER_APP_PROFILE_STRING': 'Internet Explorer',
 'FPS_BROWSER_USER_PROFILE_STRING': 'Default',
 'HOMEDRIVE': 'C:',
 'HOMEPATH': '\\Users\\User',
 'LOCALAPPDATA': 'C:\\Users\\User\\AppData\\Local',
 'LOGONSERVER': '\\\\LAPTOP-N2AJGH91',
 'NUMBER_OF_PROCESSORS': '8',
 'ONEDRIVE': 'C:\\Users\\User\\OneDrive',
 'OS': 'Windows_NT',
 'PATH': 'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python39\\Lib\\site-packages\\cv2\\../../x64/vc14/bin;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WIND

In [18]:
%matplotlib --list

Available matplotlib backends: ['tk', 'gtk', 'gtk3', 'gtk4', 'wx', 'qt4', 'qt5', 'qt6', 'qt', 'osx', 'nbagg', 'notebook', 'agg', 'svg', 'pdf', 'ps', 'inline', 'ipympl', 'widget']


In [19]:
x = 1/3
print(x)

0.3333333333333333


In [21]:
%precision 3

x

0.333

In [24]:
%time sum(range(1000000))

Wall time: 60.2 ms


499999500000

In [25]:
%who

IPython	 cv	 i	 np	 plt	 x	 


In [26]:
%who int

i	 


In [27]:
%who float

x	 


In [28]:
%%script bash
ls

Couldn't find program: 'bash'


In [30]:
!dir

 Volume in drive C is OS
 Volume Serial Number is CE4D-4ACD

 Directory of C:\Users\User\image processing\image_processing_UCCC2513

14/06/2022  09:27 AM    <DIR>          .
14/06/2022  09:27 AM    <DIR>          ..
10/06/2022  12:49 PM    <DIR>          .ipynb_checkpoints
04/06/2022  11:05 PM            13,276 coins.jfif
14/06/2022  09:27 AM            12,057 demo.ipynb
06/06/2022  10:44 AM             5,365 dog.jfif
03/06/2022  02:27 PM        22,700,438 img_pexels.mp4
03/06/2022  01:05 PM            52,378 lena.bmp
03/06/2022  01:07 PM            27,729 lena.gif
03/06/2022  01:00 PM             8,006 lena.jfif
03/06/2022  01:08 PM            17,644 lena.jpg
03/06/2022  01:07 PM           136,884 lena.png
03/06/2022  01:18 PM           131,202 lena.tif
11/06/2022  03:56 AM            18,244 lena_save.jpg
06/06/2022  04:26 PM             3,977 low_contrast_img.jfif
05/06/2022  11:00 AM            24,490 noisy.jfif
03/06/2022  03:57 PM         4,884,038 out.avi
04/06/2022  01:51 PM    

$ \sigma $

In [1]:
import numpy as np

In [ ]:
a = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]], 
             [[0, 3], [9, 1], [1, 0], [8, 1]],
             [[2, 2], [1, 1], [0, 0], [4, 5]]])

In [2]:
print(a)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]

 [[0 3]
  [9 1]
  [1 0]
  [8 1]]

 [[2 2]
  [1 1]
  [0 0]
  [4 5]]]


In [3]:
np.sum(a, axis = 0)

array([[ 3,  7],
       [13,  6],
       [ 6,  6],
       [19, 14]])

In [4]:
np.sum(a, axis = 1)

array([[16, 20],
       [18,  5],
       [ 7,  8]])

In [5]:
np.sum(a, axis = 2)

array([[ 3,  7, 11, 15],
       [ 3, 10,  1,  9],
       [ 4,  2,  0,  9]])

## Print all the magic commands

In [1]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %conda  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python 

In [2]:
%pwd

'C:\\Users\\User\\image processing\\image_processing_UCCC2513'

In [3]:
%ls

 Volume in drive C is OS
 Volume Serial Number is CE4D-4ACD

 Directory of C:\Users\User\image processing\image_processing_UCCC2513

23/06/2022  10:26 AM    <DIR>          .
23/06/2022  10:26 AM    <DIR>          ..
16/06/2022  10:43 AM    <DIR>          .ipynb_checkpoints
22/06/2022  01:48 PM           208,585 ADwithGraderFeedback.pdf
22/06/2022  01:53 PM         1,320,375 Anomaly_detection_in_Network_Traffic_Using_Unsupervised_Machine_learning_Approach.pdf
04/06/2022  11:05 PM            13,276 coins.jfif
23/06/2022  10:26 AM            21,531 demo.ipynb
22/06/2022  11:39 AM           213,427 demo_1_w5.ipynb
06/06/2022  10:44 AM             5,365 dog.jfif
21/06/2022  01:00 PM            74,894 dog.png
14/06/2022  01:36 PM             3,006 flower.jfif
21/06/2022  03:39 PM    <DIR>          image_embed
03/06/2022  02:27 PM        22,700,438 img_pexels.mp4
03/06/2022  01:05 PM            52,378 lena.bmp
03/06/2022  01:07 PM            27,729 lena.gif
03/06/2022  01:00 PM             8,